### ISSUE TITLE
[Landing Page] Add horizontally scrollable Chef Cards

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#10]
## User Story
As a **[Role]**, I would like ** to scroll through and see various cards with nearby Chefs on them** so that **I can explore my nearby Chef options and gather quick information that might catch my interest**.

## Detailed Description
Interspersed in the scrollable Dish cards on the Landing Page, there will be sections that are horizontally scrollable of various nearby Chef cards. Like Dish cards, the Chef cards will feature basic information about them and be clickable to take them to the Chef's landing page

## Acceptance Criteria
- [x] Given **Chef card clicked**, then **user is taken to Chef's Storefront**
- [x] Given **[Condition]**, then **[Expected Result]**
- [x] Given **[Condition]**, then **[Expected Result]**

## Tasks
- [x] Create Chef card div
- [x] Chef's profile picture
- [x] Chef's name
- [x] Placeholder for average rating
- [x] Placeholder for chef's location or text saying how far away they are
- [x] Text with Chef's cuisine/specialty
- [x] Add cards to Landing Page
- [x] Clicking on Chef cards takes user to Chef's Storefront
