### ISSUE TITLE
[Order Process] Reviews and Ratings Records and Averages

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#12]
## User Story
As a **User**, I would like **to know the average ratings of Dishes and Chefs and read written reviews left by other customers** so that **I can decide whether to continue ordering a certain Dish from a certain Chef or not**.

## Detailed Description
Every dish will have its own ratings and written reviews. The rating of a dish is the average star rating of the valid ratings left for that dish. A chef's rating and reviews will consist of the average of all ratings and reviews for any of their dishes. The ratings and reviews will be stored in a database indexed by chef and dish.

## Acceptance Criteria
- [x] Given **Developer runs a script**, then **database is accessible and app can pull from it**
- [x] Given **User starts Docker container**, then **Database is up and running locally**

## Tasks
- [x] Create Database for reviews
- [x] Create Database for Chefs
- [x] Create Database for Dishes
