### ISSUE TITLE
[Order Process] Cart Panel UI

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#17]
## User Story
As a **User**, I would like **to be able to view all the items currently in my cart and a preview of their picture, name, price, quantity, and special instructions** so that **I can keep track of the Dishes I am ordering**.

## Detailed Description
Be able to access my shopping cart from the major navigation screens of the Potluck app, and see what items I have added to that cart. Also, I should be able to checkout from viewing my cart so that I can order the dishes that I want to. This user experience should be streamlined and easy to navigate. In addition, I should be able to edit my shopping cart to increase/decrease the quantity of items that I want to order.

## Acceptance Criteria
- [x] Given **an empty cart**, then **there should be an indication that nothing is in the cart yet.**
- [x] Given **items in the cart**, then **their quantities can be dynamically updated, and I can see the new total prices.**
- [x] Given **I can navigate to the dish pages**, then **I can add these dishes to my cart.**
- [x] Given **I add the same dish multiple times to my cart**, then **there should not be any duplicate entries, only the quantities should be updated.**
- [x] Given **there are items in my cart**, then **I should see an indication of that from the featured menu.**
- [x] Given **I click the "Add to Cart" button from the dish page**, then **I should know that the item was added successfully.**

## Tasks
- [x] Create Cart screen/page
- [x] Connect this to the "Add to Cart" button on each dish page
- [x] Link each item in the cart back to their respective dish pages
- [x] Increase/decrease quantity from shopping cart page
- [x] Create shopping cart cards for clearer communication
- [x] Add compatibility with database updates/information
