### ISSUE TITLE
Chef's Storefront Page and Dish Pages

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#2]
## Epic
Description and User Benefit:
Each Chef (seller) will have their own Storefront (profile) where their general information, reviews, location, and available Dishes are listed. The feature allows users (buyers) to see all relevant information about a Chef in one place that may aid them in deciding whether to order from them or not, as well as providing an opportunity to discover more Dishes from the same Chef that they're interested in ordering from. From the Chef Storefront, users can click on a Dish that will take them to the specified Dish Page where the dish's image, average rating, written reviews, description, ingredients, price, estimated completion time, and Chef information can be viewed. The Dish page allows users to get information on the Dish to help them decide whether to order it or if there are any ingredients that violate their dietary restrictions.

Each Storefront will feature:
- The Chef's profile picture
- A short bio written by the Chef
- Location
- Average star rating
- A few featured written reviews by customers
- Menu featuring Dishes that are available right now and Dishes they have made in the past. Dishes unavailable at the moment will be grayed out but still clickable

Each Dish Page will feature:
- Dish picture
- Price
- Description
- Average Rating
- A few featured written reviews by customers
- Ingredients
- Estimated order completion time
- General information about the chef including location

#### User Actions and Requirements:
Storefront:
- The user should be able to click on the rating or the featured written reviews to view the rest of the written customer reviews.
- The user should be able to click on the location and an enlarged map UI will pop up showing the user's location and the Chef's location
- The user should be able to scroll through the Chef's Dishes, with available ones first and bold.
- The user should also be able to scroll to the Chef's past Dishes, but they will be marked as unavailable and grayed out
- The user should be able to click on any Dish that will take them to that Dish's page

Dish Pages:
- The user should be able to scroll through images of the dish
- The user should be able to click on the rating of the dish and view reviews for that specific dish just like for the Chef's storefront
- The user should be able to click on the Chef's location and see an enlarged map just like for the Chef's storefront
- The user should be able to click on the Chef's general information and be taken to the Chef's Storefront.

## User Stories
- [x] Dish Page UI with Dish information #7
- [x] Dish Ratings and Reviews #13
- [x] Chef's Storefront UI with profile and general info #8
- [x] Chef's Ratings and Reviews #14
- [x] Add Chef's Menu UI to the Storefront featuring Dish cards #11
- [x] Chef's Location #15
- [x] Add Chef's information and location to Dish UI #16
