### ISSUE TITLE
[Order Process] Order Tracking Panel

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#20]
## User Story
As a **User**, I would like **to be able to track what state my order is in and where it is along with an estimated delivery time** so that **I can anticipate when my order will arrive**.

## Detailed Description
Page that gets navigated to after payment submission where you can see what stage your order is in as well as a summary of your order.

## Acceptance Criteria
- [x] Create Order table in db
- [x] Submitting payment from checkout screen pushes order to db
- [x] order progress is tracked and displayed until marked as delivered by chef
