### ISSUE TITLE
Landing Page AKA Featured Menu

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#3]
## Epic
Description and User Benefit:
The landing page and main panel of the application will be the Featured Menu. On this page, users will be able to scroll through currently available Dishes near them and filter/sort by location, price, dish type, and cuisine. Interspersed in the vertical scrolling list of Dish cards, there will be panels of Chefs near the user that can be scrolled through horizontally. This landing page allows users to explore Dish options as well as look at near, popular, and highly rated Chefs. The main page serves as a way to view the Potluck community of chefs and their offerings, connecting to hungry users exploring for their next meal/snack. 

Featured Menu features:
- Vertical scrollable Dish cards featuring the dish picture, price, name, Chef (with a small profile picture), completion time, average rating
- Dish-card-height Chef lists interspersed in the Dish list that are horizontally scrollable. Chef cards feature the Chef's profile picture, name, average rating, and dish type/cuisine specialty
- At the top of the application will be a Menu Bar where the user's delivery address is shown and can be changed.

#### User Actions and Requirements
- Users can pull down and refresh the page
- Only available dishes and chef's with currently available dishes will be shown
- Users can click on a Dish Card and be taken to its Dish Page
- Users can click on the profile picture of a Chef within a Dish Card and be taken to the Chef's Storefront
- Users can click on a Chef's Card and be taken to their Chef's Storefront
- Users should be able to click on the top bar and change their delivery address

## User Stories
- [x] Initialize Basic/Fundamental App Structure #6 
- [x] Add scrollable/clickable Dish Cards #9
- [x] Add horizontally scrollable Chef Cards #10
- [x] Filters and Sorting functionality #23
