### ISSUE TITLE
Order Process

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#4]
## Epic
Description and User Benefit:
Purchasing, Checkout, Reviews, Fulfillment Process
Upon selection of a meal, the user should swiftly be able to add the dish to their cart, view their cart, and checkout within the app. After checking out, they should be able to track the progress and delivery of their meal until delivery. After receiving the meal, the user should be prompted to leave a rating and a review for the dish. This allows users to keep track of the meals they are buying, and to easily purchase them and begin the meal preparation/delivery process. The Chefs should also be notified when a purchase of one of their meals is made so they can start preparations. The users will be able to track how much estimated time is left in its preparation process so they can be ready for their food when it arrives. Reviews will also help Chefs get feedback on their performance and dish quality, as well as help users decide which dishes to order and from whom.

#### User Actions and Requirements:
- A Dish's average rating should be the average of all valid star ratings left by customers for that dish.
- A Chef's average rating should be the average of all valid star ratings left by customers for any of their dishes
- A Dish's written reviews should include any written review left by a customer on that dish
- A Chef's written reviews should include any written review left by a customer on any of their dishes
- When a user adds a Dish to their cart, they should be able to write special instructions, select a quantity, and confirm their Dish order.
- After the user confirms the Dish order, it should be viewable in their Cart.
- When a user clicks on a Dish in their Cart, they should be able to view the Dish's page and a summary of the order's special instructions and quantity
- There should be a button on the top menu of the app that allows the user to access their Cart.
- In the Cart, a user should be able to click Checkout and begin the checkout process
- Through a Credit Card API or Venmo API, the user should have some way of paying for their meal.
- After paying for the meal and confirming the order, the user should be taken to a screen which tracks the progress and location of the order.
- After the order is delivered, the user should be prompted to review their order, having the option to leave a star rating and a written review for each different dish they ordered.

## User Stories
- [x] Reviews and Ratings Records and Averages #12
- [x] Cart Panel UI #17
- [x] Add Dish to Cart Interface #18
- [x] Checkout Cart/Payment Interface #19
- [x] Order Tracking Panel #20
- [x] Review Prompt After Delivery #22
