### ISSUE TITLE
Search Assistance

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#5]
## Epic
Description and User Benefit:
Search Assistance will benefit the user by helping them refine their searches for Dishes and Chefs more specifically, showing more relevant results. There will be a button on the top menu bar of the app that allows users to type in what they are searching for whether it is a Chef's name, Dish name, Dish type, cuisine, or ingredients and they will be able to view results sorted by relevance. There will also be a button on the top menu bar of the app that takes users to a map interface where they can see their location and nearby pins that signify Chef locations. This map functionality helps users search for meals and chefs by proximity.

#### User Actions and Requirements
- User should be able to click on spyglass icon in the top menu bar and be given the option to input text
- Upon searching, users should be returned relevant search results organized into Dishes and Chefs
- Search results should be relevant, encompassing Dish title, Dish type, cuisine, ingredients, Chef's name, etc.
- User should be able to click on map icon in the top menu bar and be taken to a map interface
- User should be able to click on a pin on the map and see the Chef's picture, name, rating, and available dishes and their prices.
- User should be able to click on Chef's card or Chef's profile picture to be taken to that Chef's Storefront
- User should be able to click on Dish card or Dish name to be taken to that Dish's Page

## User Stories
- [x] Search Icon, Search Bar, and Results Interface #24
- [x] Refined Search Algorithm #25
- [x] Map Icon, Map Interface #26 
- [x] Map Pin Interface #27
