### ISSUE TITLE
[Landing Page] Initialize Basic/Fundamental App Structure

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#6]
## User Story
As a **User**, I would like **to open the app and be taken to the main landing page with a menu bar on top** so that **I can scroll through meals and chefs and access Search and Map functionality**.

## Detailed Description
Main panel of the app and main UI. This story involves setting up the React-Native app and getting a skeleton UI started to build off of.
The landing page will consist of the main scrollable panel and a menu bar on the top of the screen with icons to access various functionalities.

## Acceptance Criteria
- [x] Given **User Opens app**, then **Splash Screen renders then Featured Menu Screen Opens**
- [x] Given **User Scrolls down**, then **There are placeholders for Dish and Chef cards**
- [x] Given **User Scrolls down**, then **NavBar stays at the top of the screen**

## Tasks
- [x] Create React-Native App
- [x] Create NavBar
- [x] Create Scrollable panel
- [x] Create skeleton for Dish Cards
