### ISSUE TITLE
[Storefront and Dish Pages] Dish Page UI with Dish Information

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#7]
## User Story
As a **User**, I would like **click on Dishes and be taken to a new page for that Dish** so that **I can view all information about that Dish and its Chef and add it to my cart**.

## Detailed Description
Each Dish will have a Dish page that contains all relevant information about it. From here, customers can add the dish to their cart. This story includes initializing the structure of the Dish pages and adding basic general information about the dish.

## Acceptance Criteria
- [x] Given **a certain dish**, then **Dish Page renders correct information from that specific dish**
- [x] Given **Dish Card is Clicked**, then **Dish Page Renders**
- [x] Given **User Clicks on Dish Picture**, then **Picture enlarges and can be scrolled through**

## Tasks
- [x] Set up Dish database
- [x] Dish Page skeleton
- [x] Dish Pictures
- [x] Dish Name
- [x] Dish Price
- [x] Dish Description
- [x] Dish Ingredients
- [x] Estimated order completion time
- [x] Add to cart skeleton button
- [x] Connect with Backend Dish Database
