### ISSUE TITLE
[Storefront and Dish Pages] Chef's Storefront UI with profile and general info

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#8]
## User Story
As a **User**, I would like **to be able to click on a Chef and be taken to a new page for that Chef** so that **I can view all information about the Chef and view their current and past available Dishes**.

## Detailed Description
Each Chef will have a Storefront page that serves as their "profile." This story includes initializing the structure of the Storefront and adding basic general information about the chef.

## Acceptance Criteria
- [x] Given **someone clicking on the chef card of the dish card**, then **the chef screen shows up**
- [x] Given **a user scrolling through the chefs page**, then **all the dishes that the chef has will be shown in a table, along with a chef picture and bio**
- [x] Given **a click on a dish on the chef's page**, then **it will navigate to the dish page so they can purchase it**

## Tasks
- [x] Create Chef database
- [x] Storefront page skeleton
- [x] Chef Profile picture
- [x] Chef's bio
