### ISSUE TITLE
[Landing Page] Add scrollable/clickable Dish Cards

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#9]
## User Story
As a **User**, I would like **to scroll through the Landing Page and see various cards with dishes on them** so that **I can explore my dish options and gather quick information that might catch my interest**.

## Detailed Description
Add Dish Cards to the Landing Page UI. Dish Cards will feature a picture of the dish, the dish's name, the price, its estimated order completion time, its average rating, and the Chef's name and profile picture. When the Dish card is clicked, the user should be taken to the Dish's page.

## Acceptance Criteria
- [x] Given **Dish card clicked**, then **user is taken to the Dish's Dish page**
- [x] Given **Dish cards appearing on my phone's screen**, then **I should see information about the dish (chef, image, rating, description).**

## Tasks
- [x] Create Dish card div
- [x] Dish picture
- [x] Dish name
- [x] price
~- [ ] estimated order completion time --> inside dish page~
- [x] placeholder for average rating
- [x] Chef's name
- [x] Chef's profile picture
- [x] Add cards to Landing Page
- [x] Clicking on dish navigates to dish page
